import { useMemo } from 'react';
import { StyleSheet } from 'react-native';
import { useTheme } from '../../../../styles';

export const useStyles = () => {
  const { theme } = useTheme();
  return useMemo(
    () =>
      StyleSheet.create({
        container: {
          flex: 1,
          backgroundColor: theme.colors.background,
        },
        scrollContent: {
          paddingBottom: theme.spacing.xxl,
          paddingTop: theme.spacing.xxxl,
        },
        battleArena: {
          height: 400,
          position: 'relative',
          paddingTop: theme.spacing.lg,
        },
        cardWrapper: {
          position: 'absolute',
          width: 170,
          alignItems: 'center',
        },
        cardLeft: {
          left: 30,
          top: 50,
        },
        cardRight: {
          right: 30,
          top: 20,
          zIndex: 10,
        },
        card: {
          width: '100%',
          aspectRatio: 3 / 4,
          borderRadius: theme.radius.md,
          overflow: 'hidden',
          backgroundColor: theme.colors.card,
          borderColor: theme.colors.border,
          borderWidth: 2,
          shadowColor: theme.colors.textDark,
          shadowOpacity: 0.15,
          shadowRadius: 12,
          shadowOffset: { width: 0, height: 6 },
          elevation: 8,
        },
        cardImage: {
          width: '100%',
          height: '100%',
        },
        cardName: {
          marginTop: theme.spacing.md,
          fontSize: theme.typography.size.md,
          fontWeight: '700',
          color: theme.colors.text,
        },
        cardNameWinner: {
          marginTop: theme.spacing.md,
          fontSize: theme.typography.size.md,
          fontWeight: '700',
          color: theme.colors.success,
        },
        winTag: {
          position: 'absolute',
          top: 0,
          right: 28,
          backgroundColor: theme.colors.success,
          paddingHorizontal: theme.spacing.md,
          paddingVertical: theme.spacing.xs,
          borderRadius: theme.radius.md,
          zIndex: 10,
        },
        winTagText: {
          color: theme.colors.surface,
          fontSize: theme.typography.size.md,
          fontWeight: '900',
        },
        loseTag: {
          position: 'absolute',
          top: 32,
          left: 28,
          backgroundColor: theme.colors.loserBadge,
          paddingHorizontal: theme.spacing.md,
          paddingVertical: theme.spacing.xs,
          borderRadius: theme.radius.md,
          zIndex: 10,
        },
        loseTagText: {
          color: theme.colors.surface,
          fontSize: theme.typography.size.md,
          fontWeight: '900',
        },
        scoreBox: {
          marginTop: theme.spacing.sm,
          backgroundColor: theme.colors.card,
          paddingHorizontal: theme.spacing.lg,
          paddingVertical: theme.spacing.sm,
          borderRadius: theme.radius.md,
          borderWidth: 2,
          borderColor: theme.colors.border,
          minWidth: 120,
          alignItems: 'center',
        },
        scoreBoxWinner: {
          marginTop: theme.spacing.sm,
          backgroundColor: theme.colors.success,
          paddingHorizontal: theme.spacing.lg,
          paddingVertical: theme.spacing.sm,
          borderRadius: theme.radius.md,
          minWidth: 120,
          alignItems: 'center',
        },
        scoreLabel: {
          fontSize: theme.typography.size.xs,
          textTransform: 'uppercase',
          color: theme.colors.textSecondary,
          fontWeight: '600',
        },
        scoreLabelWinner: {
          fontSize: theme.typography.size.xs,
          textTransform: 'uppercase',
          color: theme.colors.surface,
          fontWeight: '700',
        },
        scoreValue: {
          fontSize: theme.typography.size.xl,
          fontWeight: '900',
          color: theme.colors.text,
        },
        scoreValueWinner: {
          fontSize: theme.typography.size.xl,
          fontWeight: '900',
          color: theme.colors.surface,
        },
        vsCircle: {
          position: 'absolute',
          top: '45%',
          left: '50%',
          transform: [{ translateX: -28 }, { translateY: -28 }],
          width: 56,
          height: 56,
          borderRadius: theme.radius.xl,
          backgroundColor: theme.colors.surface,
          borderWidth: 3,
          borderColor: theme.colors.border,
          alignItems: 'center',
          justifyContent: 'center',
          elevation: 8,
          zIndex: 10,
        },
        vsText: {
          fontSize: theme.typography.size.md,
          fontWeight: '900',
          color: theme.colors.text,
        },
        statusText: {
          textAlign: 'center',
          color: theme.colors.textSecondary,
          marginBottom: theme.spacing.md,
          fontWeight: '600',
        },
        errorText: {
          textAlign: 'center',
          color: theme.colors.danger,
          marginBottom: theme.spacing.md,
          fontWeight: '600',
        },
        section: {
          backgroundColor: theme.colors.surface,
          marginTop: theme.spacing.xl,
          marginHorizontal: theme.spacing.lg,
          borderRadius: theme.radius.lg,
          padding: theme.spacing.xl,
          elevation: 4,
        },
        sectionTitle: {
          fontSize: theme.typography.size.lg,
          fontWeight: '700',
          color: theme.colors.text,
          marginBottom: theme.spacing.lg,
        },
        powerGrid: {
          flexDirection: 'row',
          gap: theme.spacing.md,
        },
        playerCol: {
          flex: 1,
          gap: theme.spacing.md,
        },
        playerName: {
          fontSize: theme.typography.size.md,
          fontWeight: '700',
          color: theme.colors.textSecondary,
          textAlign: 'center',
        },
        playerWinner: {
          color: theme.colors.success,
        },
        powerCard: {
          backgroundColor: theme.colors.card,
          borderRadius: theme.radius.md,
          padding: theme.spacing.md,
          alignItems: 'center',
          borderWidth: 2,
          borderColor: theme.colors.border,
        },
        powerCardWinner: {
          backgroundColor: theme.colors.winnerBadge,
          borderColor: theme.colors.success,
        },
        powerLabel: {
          fontSize: theme.typography.size.xs,
          fontWeight: '600',
          color: theme.colors.textSecondary,
          textTransform: 'uppercase',
        },
        powerLabelWinner: {
          fontSize: theme.typography.size.xs,
          fontWeight: '700',
          color: theme.colors.surface,
          textTransform: 'uppercase',
        },
        powerValue: {
          fontSize: theme.typography.size.xl,
          fontWeight: '800',
          color: theme.colors.text,
        },
        powerValueWinner: {
          fontSize: theme.typography.size.xl,
          fontWeight: '800',
          color: theme.colors.surface,
        },
        statsTable: {
          backgroundColor: theme.colors.card,
          borderRadius: theme.radius.md,
          borderWidth: 2,
          borderColor: theme.colors.border,
          overflow: 'hidden',
        },
        statsHeader: {
          flexDirection: 'row',
          backgroundColor: theme.colors.background,
          paddingVertical: theme.spacing.md,
        },
        headerCell: {
          flex: 1,
          textAlign: 'center',
          fontWeight: '700',
          color: theme.colors.text,
        },
        headerCellCenter: {
          flex: 1,
          textAlign: 'center',
          color: theme.colors.textSecondary,
          fontWeight: '700',
        },
        statRow: {
          flexDirection: 'row',
          paddingVertical: theme.spacing.md,
          borderBottomWidth: 1,
          borderBottomColor: theme.colors.border,
        },
        statCell: {
          flex: 1,
          alignItems: 'center',
          paddingVertical: theme.spacing.xs,
        },
        statLabel: {
          flex: 1,
          alignItems: 'center',
        },
        statLabelText: {
          fontSize: theme.typography.size.sm,
          fontWeight: '600',
          color: theme.colors.textSecondary,
        },
        statValue: {
          fontSize: theme.typography.size.md,
          fontWeight: '600',
          color: theme.colors.text,
        },
        winnerCell: {
          backgroundColor: theme.colors.winnerBadge,
        },
        winnerText: {
          color: theme.colors.surface,
          fontWeight: '700',
        },
        loaderAnimation: {
          width: '100%',
          height: 420,
        },
      }),
    [theme],
  );
};
