export const ENERGY_EMOJI: Record<string, string> = {
  metal: '⚙️',
  steel: '⚙️',
  fire: '🔥',
  water: '💧',
  lightning: '⚡️',
  electric: '⚡️',
  grass: '🌱',
  psychic: '🔮',
  fighting: '👊',
  darkness: '🌑',
  dark: '🌙',
  dragon: '🐉',
  fairy: '🧚',
  colorless: '⚪',
  normal: '✨',
  ice: '❄️',
  rock: '🪨',
  ground: '⛰️',
  bug: '🐛',
  ghost: '👻',
};
